CREATE TABLE T_COUNTRY
(
  ID                RAW(16)                     NOT NULL,
  VERSION           NUMBER(10)                  NOT NULL,
  COUNTRY           VARCHAR2(3 CHAR)            NOT NULL,
  MEANING           VARCHAR2(70 CHAR),
  ISO_COUNTRY_CODE  VARCHAR2(3 CHAR),
  ISO_COUNTRY_NO    VARCHAR2(3 CHAR),
  CONSTRAINT T_COUNTRY_ID_PK
 PRIMARY KEY
 (ID)
);

INSERT INTO T_COUNTRY (ID, VERSION, COUNTRY, MEANING) VALUES ('00000000000000000000000000000000',0,'FRA','FRANCE');